name: jaguar_jwt
description: Provides JWT utilities for Dart including issuing a token, verifing a token and parsing a token.
version: 3.0.0
homepage: https://github.com/geckonz/jaguar-dart
repository: https://github.com/geckonz/jaguar-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.8
